#连接池
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fast?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: itfeiyue
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  redis:
    database: 1
    host: 119.3.204.184
    port: 6379
# 日志配置
logging:
  level:
    my.fast.admin: debug
  config: classpath:logback.xml
# 开启调试模式
debug: false
