#连接池
spring:
  datasource:
    url: jdbc:mysql://192.168.2.4:3306/fast?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: itfeiyue
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  redis:
    database: 1
    host: 119.3.204.184
    port: 6379
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
# 日志配置
logging:
  level:
    my.fast.admin: debug
  config: classpath:logback.xml
# 开启调试模式
debug: false
s3:
  storage:
    accessKeyId: 4H742JA6U3TR5OICBEJM
    secretAccessKey: pZMMiIxC0gK0LdIL9H1D5Ha+1B5o79xJSkLy947AebE
    endpoint: sgp1.digitaloceanspaces.com
    bucketName: ppp
    sdkVersion: latest
    region: sgp1
    storageFilePath: /ppp/images